PUT https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index-video?api-version=2023-07-01-Preview
content-type: application/json
api-key: wCOk7nDtw14N9pXcx80U5CHBpVNZjM9KnCHpqSJfKfAzSeBy7mkr

{
    "name": "aiath-sample-index-video",
    "fields": [
      {
        "name": "id",
        "type": "Edm.String",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "metadata_storage_name",
        "type": "Edm.String",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": true,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "durationInSeconds",
        "type": "Edm.Double",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": true,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "video_indexer_url",
        "type": "Edm.String",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "language",
        "type": "Edm.String",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": true,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "merged_content",
        "type": "Edm.String",
        "searchable": true,
        "filterable": false,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": "th.lucene",
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "metadata_storage_path",
        "type": "Edm.String",
        "searchable": false,
        "filterable": false,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": true,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "transcript",
        "type": "Collection(Edm.String)",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "ocr",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "keywords",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": "th.lucene",
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "topics",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": true,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": "th.lucene",
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "faces",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "labels",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": "th.lucene",
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "brands",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": true,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "namedLocations",
        "type": "Collection(Edm.String)",
        "searchable": true,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "namedPeople",
        "type": "Collection(Edm.String)",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      },
      {
        "name": "sentiments",
        "type": "Edm.Double",
        "searchable": false,
        "filterable": true,
        "retrievable": true,
        "sortable": false,
        "facetable": false,
        "key": false,
        "indexAnalyzer": null,
        "searchAnalyzer": null,
        "analyzer": null,
        "normalizer": null,
        "dimensions": null,
        "vectorSearchConfiguration": null,
        "synonymMaps": []
      }
    ],
    "scoringProfiles": [],
    "corsOptions": null,
    "suggesters": [],
    "analyzers": [],
    "normalizers": [],
    "tokenizers": [],
    "tokenFilters": [],
    "charFilters": [],
    "encryptionKey": null,
    "similarity": {
      "@odata.type": "#Microsoft.Azure.Search.BM25Similarity",
      "k1": null,
      "b": null
    },
    "semantic": null,
    "vectorSearch": null
  }