DELETE https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index-video?api-version=2020-06-30
content-type: application/json
api-key: wCOk7nDtw14N9pXcx80U5CHBpVNZjM9KnCHpqSJfKfAzSeBy7mkr
