POST https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index-video/docs/index?api-version=2020-06-30
content-type: application/json
api-key: wCOk7nDtw14N9pXcx80U5CHBpVNZjM9KnCHpqSJfKfAzSeBy7mkr

{
  "value": [
    {
      "@search.action": "mergeOrUpload",  
      "id": "c2a1a61362",
      "metadata_storage_name": "post_images_record_2.mp4",
      "durationInSeconds": 135,
      "video_indexer_url": null,
      "language": "th-TH",
      "merged_content": "",
      "metadata_storage_path": "aHR0cHM6Ly92aWRlb2ttbGtnN2V2LmNvcmUud2luZG93cy5uZXQvdmlkZW8ta25vd2xlZGdlLW1pbmluZy9jMmExYTYxMzYyLmpzb24=",
      "transcript": [
        "ว้ายตายได้ตอบดีตอบทีดีมีรางวัลอยากรู้ไหมครับทำไมแม่มดต้องขี่ไม้กวาดไปค่ะ",
        "นะคะหรือยัง",
        "ความเชื่อนี้นะคะมันเป็นความเชื่อของชาวนานอกรีตในยุโรปสมัยก่อนค่ะเขาเชื่อว่าในคืนพระจันทร์เต็มดวงนี้นะคะเขาเนี่ยจะออกมาเต้นรำกันนะคะท่ามกลางแสงจันทร์โดยที่บางคนเนี่ยก็จะถือไม้กวาดมาบ้างถือจอบซื้อเสียมมาบ้างนะคะแล้วเขาเชื่อว่าการที่เราเนี่ยพี่ค่อมหรือกระโดดข้ามเนี่ยมันจะทำให้ผลผลิตทางการเกษตรในปีเนี้ยมันดีและสมบูรณ์มากๆค่ะแต่ก็มีอีกคใส่ถ่านอีกนะคะไม่แน่ว่าการที่แม่โหมดเนี่ยขี่ไม้กวาดได้เนี่ยอาจจะมาจากการหลอนยาหรือเสพยาก็ได้นะคะ",
        "ในช่วงยุคกลางนะคะคนยุโรปเนี่ยเขานิยมกินขนมปังสิทธิ์นึงค่ะชื่อว่าขนมปังร้ายนะคะโดยในข่าวร้ายนะคะจะมีเชื้อราชื่อเอ้ยแกะซึ่งในขนมปังชนิดนี้นะคะถ้าเกิดกินมากเกินไปเนี่ยเชื้อราในหน้านะคะมา 3 ารถสร้างภาพหลอนหรือเป็นศาสตร์หลอดประสาทให้เราได้นะคะในการเสพสารอันนี้นะคะมันมีอีกวิธี หนึ่ง ที่เขานิยมใช้ก็คือเขาจะเอาสาดเนี่ยทาวน์ที่ด้ามไม้กวาดค่ะแล้วเขาก็จะขึ้นค่อมนะคะขี่อย่างเงี้ยค่ะทำให้สารเนี่ยมันค่อยซึมเข้าสู่ร่างกายนะคะดังนั้นเขาเลยคิดว่าการที่เขาเนี่ยขี่ไม้กวาดหรือขึ้นไปนั่งบนไม้กวาดเนี่ยมัน 3 ารถบินได้นั่นเองค่ะ",
        "และในเวลาต่อมานะคะศาสนจักรค่ะเขาก็ได้บอกว่าการทำอะไรแบบนี้ครับมันเป็นการทำที่นอกรีตมากๆคนที่ทำแบบนี้เนี่ยคือคนที่เป็นแม่มดนั่นเองค่ะคือนี้ยัง",
        "ขอให้ท่านผู้ชมทุกท่านได้รับความรู้และความสนุกจากคลิปนี้ด้วยนะคะโอมเพี้ยงเมีย 19 19 รุ่นโมเอบีมไอไหลหรือยัง",
        "ว้ายตายได้ตอบดีตอบทีดีมีรางวัลคำถามมาแล้วนะคะแม่มดถ้าเกิดไม่ขี่ไม้กวาดคีย์อะไรดีหน้า 20 ครั้งแรกนะคะพี่ตอบคำถามถูกใจกันมากันไม่ว่าจะเป็นความคิดสร้างสรรค์เชิงวิชาการคือแม้แต่ตบคันนะคะรับไปเลยช้อปปี้อีวอยเชอร์มูลค่า 100 บาทค่ะกิจกรรมนี้ค่ะขอสงวนสิทธิ์สำหรับผู้ที่ยังไม่เคยได้รับรางวัลจากทางเรานะคะหรือนี้ยัง"
      ],
      "ocr": [
        "Alive",
        "Powered by AIA",
        "ENJOY NON-STOP",
        "nec",
        "RYE",
        "(RYE)",
        "ERGOT"
      ],
      "keywords": [
        "enjoy non",
        "ว้ายตายได้ตอบดีตอบทีดี",
        "อีกคใส่ถ่านอีกนะคะไม่แน่ว่าการที่แม่โหมดเนี่ยขี่ไม้กวาดได้เนี่ยอาจจะมาจากการหลอนยาหรือเสพยาก็",
        "เขานิยมใช้",
        "คือเขาจะเอาสาดเนี่ยทาวน์",
        "บอกว่าการทำอะไรแบบนี้ครับมันเป็นการทำที่นอกรีตมากๆคนที่ทำแบบนี้เนี่ยคือคนที่เป็นแม่มดนั่นเองค่ะคือนี้",
        "ยังไม่เคยได้รับรางวัลจากทางเรานะคะหรือนี้",
        "alive",
        "stop",
        "ergot"
      ],
      "topics": [
        "ศาสนา",
        "ศาสนาคริสต์",
        "วิทยาศาสตร์"
      ],
      "faces": [
        "Unknown #1"
      ],
      "labels": [
        "ข้อความ",
        "ใบหน้ามนุษย์",
        "เสื้อผ้า",
        "คน",
        "ยิ้ม",
        "ภาพเหมือน",
        "หมวก",
        "ต้นไม้",
        "หุ้ม",
        "เครื่องประดับแฟชั่น",
        "นามบัตร",
        "เสื้อเบลเซอร์",
        "ชุดทางการ",
        "ผู้ชาย",
        "สูท"
      ],
      "brands": [
        "NEC"
      ],
      "namedLocations": [
        "Europe",
        "town"
      ],
      "namedPeople": [
        "God",
        "Moebeam"
      ]
    },
    {
      "@search.action": "mergeOrUpload",
      "id": "e44ba32be8",
      "metadata_storage_name": "post_images_record_4.mp4",
      "durationInSeconds": 106,
      "video_indexer_url": null,
      "language": "th_TH",
      "merged_content": "",
      "metadata_storage_path": "aHR0cHM6Ly92aWRlb2ttbGtnN2V2LmNvcmUud2luZG93cy5uZXQvdmlkZW8ta25vd2xlZGdlLW1pbmluZy9lNDRiYTMyYmU4Lmpzb24=",
      "transcript": [
        "อ๋อ",
        "เก๋าเหรออยากรู้มั้ย",
        "ไม่เรียกว่าต้มกุ๊ยอ่ะนี่เอาเลย",
        "หรือนิยัง",
        "เขาต้องคุยนะคะมันคือข้าวต้มเปล่าคะที่เรากินกับข้าวค่ะไม่ว่าจะเป็นไชเท้าดองหรือว่าจะเป็นกะหล่ำปลีดองไข่เค็มก็กินนะคะที่สำคัญหมูหวานอื้มพูดแล้วก็น้ำลายแตกค่ะแต่สงสัยกันไหมคะว่าเค้าทำไมเราถึงเรียกว่าเข้าต้มกุ๊ยที่มานะครับมันก็มาจาก สอง อย่างด้วยกันนะคะแบบแรกก็คือคำว่ากุ้ยนึกว่าสารทจีนนะครับแต่ว่าพี่คะพี่แบบแพร่อย่างเงี้ยค่ะแต่แน่นอนครับว่าคนไทยเราเนี่ยจะระบุคำว่ากุยเนี่ยหมายถึงกลุ่มคนใช้แรงงานกรรมกรหรือว่าอันธพาลเนี่ยก็ถือว่าเป็นกุ้ยเหมือนกันราคาในความเป็นคนไทยค่ะซึ่งในสมัยก่อนค่ะ",
        "เห็นว่าสมัยก่อนนะคะจะเป็นแรงงานชาวจีนค่ะที่เขาเข้ามาทำงานในประเทศไทยค่ะแล้วมันก็จะไปสอดคล้องกับอีกแนวคิด หนึ่ง นะคะว่าเมื่อก่อนเนี่ยคนงานชาวจีนเขาจะกินข้าวต้มเป็นหลักค่ะเพราะว่ามันทั้งอิ่มสะดวกแล้วก็ที่สำคัญคือราคาไม่แพงค่ะถ้าเกิดสังเกตดีๆนะคะว่าเขาต้องคุยเนี่ยมันจะเปิดกันจนโต้รุ่งค่ะและอีกแนวคิด หนึ่ง นะคะคำว่ากุยเนี่ยมันเทียนเข้ามาถามว่าคุยข่าวค่ะคุยข่าวคืออะไรคุยข่าวนะคะมันคือการที่คนจีน",
        "เค้ากินข้าวต้มเนี่ยเค้าจะใส่ถ้วยใช่ไหมค่ะแล้วใช้ตะเกียบในการกินอย่างนี้เค้าเรียก",
        "ว่าการคุยค่านั่นเองค่ะ",
        "รูนี่ย์ยัง",
        "สุดท้ายนี้นะคะก็อยากจะฝากไว้ว่าเพราะสุบรรณนี้ไม่ว่าหากใดๆก็ไม่มีสั้นๆแล้วใครๆก็ 3 ารถกินของอร่อยได้ทั้งนั้นซึ่งเดียวกับดิฉันที่อร่อยดูคนมาลิ้มรสความอร่อยอยู่นะคะอย่าลืมติดตามนะคะว่าในตอนต่อไปดิฉันจะเอาความรู้ดีๆคู่ความสนุกอะไรมาเสนอพูดได้เลยค่ะว่าสนุกและมีความรู้อย่างแน่นอนค่ะ",
        "หรือนี้ยัง"
      ],
      "ocr": [
        "Alive",
        "Powered by AIA",
        "BM"
      ],
      "keywords": [
        "นะคะว่าเมื่อก่อนเนี่ยคนงานชาวจีนเขาจะกินข้าวต้มเป็นหลักค่ะเพราะว่ามันทั้งอิ่มสะดวกแล้วก็",
        "สำคัญคือราคาไม่แพงค่ะถ้าเกิดสังเกตดีๆนะคะว่าเขาต้องคุยเนี่ยมันจะเปิดกันจนโต้รุ่งค่ะและอีกแนวคิด",
        "สุดท้ายนี้นะคะก็อยากจะฝากไว้ว่าเพราะสุบรรณนี้",
        "ว่าหากใดๆก็",
        "alive"
      ],
      "topics": [
        "อาหาร",
        "สูตร",
        "การกินเจ",
        "ภาษาอังกฤษ",
        "อาหารจีน",
        "มังสวิรัติ"
      ],
      "faces": [
        "Unknown #1",
        "Unknown #2",
        "Unknown #3",
        "Unknown #4"
      ],
      "labels": [
        "เสื้อผ้า",
        "คน",
        "เสื้อนอก",
        "ใบหน้ามนุษย์",
        "ตึก",
        "ผู้ชาย",
        "ถนน",
        "รองเท้า",
        "ยีนส์",
        "ข้อความ",
        "แว่นตากันแดด",
        "ผู้หญิง",
        "กลางแจ้ง",
        "ยิ้ม",
        "ฉาก"
      ],
      "brands": [],
      "namedLocations": [
        "Thai",
        "Chinese",
        "Thailand"
      ],
      "namedPeople": [
        "Gui Nia Mantian",
        "Rooney Young",
        "suban"
      ]
    }
  ]
}