POST https://frlai-cog-search-demo-svc.search.windows.net/indexes/good-books/docs/autocomplete?api-version=2020-06-30
content-type: application/json
api-key: sr3A6ZbzRuuUHWdeDWe1JspdXYEEq9ykdobly7qoR9AzSeCH2V30
    
    {
        "search": "c",
        "autocompleteMode": "oneTerm",
        "top": 5,
        "suggesterName": "sg"   
    }
