@api-version=2020-06-30
#@search-words=รางวัลพิเศษ
@search-words=Special Rewards
@select-fields=id,post_id,reward_th,reward_en
#@search-fields=reward_th
@search-fields= reward_en
@options=&searchMode=all

GET https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index/docs?api-version={{api-version}}&search={{search-words}}&$select={{select-fields}}&searchFields={{search-fields}}{{options}}
content-type: application/json
api-key: CQy9IWaYfKQe1mvMrG2YfHsBBE6IIcmJfTw9ywjsXgAzSeABktUj
