@api-version=2023-11-01
@search-words=fantastic
@select-fields=id,post_body_en
@search-fields=post_body_en
@options=&queryType=semantic&semanticConfiguration=default&&answers=extractive|threshold-0.7&captions=extractive




GET https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index/docs?api-version={{api-version}}&search={{search-words}}&$select={{select-fields}}&searchFields={{search-fields}}{{options}}
content-type: application/json
api-key: CQy9IWaYfKQe1mvMrG2YfHsBBE6IIcmJfTw9ywjsXgAzSeABktUj
