@api-version=2020-06-30
@search-words=โรงแรม
@select-fields=id,article_id,article_title,article_body
@search-fields=article_body
@options=&searchMode=all

GET https://cog-srch-frlai-demo-eus-01.search.windows.net/indexes/aiath-sample-index/docs?api-version={{api-version}}&search={{search-words}}&$select={{select-fields}}&searchFields={{search-fields}}{{options}}
content-type: application/json
api-key: CQy9IWaYfKQe1mvMrG2YfHsBBE6IIcmJfTw9ywjsXgAzSeABktUj
